version: 2.1

jobs:
  lint:
    docker:
      - image: rust
    steps:
      - checkout
      - run:
          name: Install cargo fmt
          command: rustup component add rustfmt
      - run:
          name: Run lint
          command: cargo fmt -- --check

  clippy:
    docker:
      - image: rust
    steps:
      - checkout
      - run:
          name: Install cargo clippy
          command: rustup component add clippy
      - run:
          name: Run Clippy
          command: cargo clippy -- -W clippy::pedantic

  build_and_test:
    machine: true
    parameters:
      toolchain:
        description: rust toolchain
        type: string

    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout
      - setup_remote_docker:
        version: 19.03.13
      - run: |
          sudo python -m pip install --upgrade pip setuptools wheel
          sudo python -m pip install pipenv
      - run: |
          pip install localstack
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
          /home/circleci/.local/bin/localstack start
      - run: >
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | 
          sh -s -- -v -y --profile minimal --default-toolchain <<parameters.toolchain>>
      - run: $HOME/.cargo/bin/cargo build
      - run: $HOME/.cargo/bin/cargo test --locked  --no-fail-fast --lib
      - run: $HOME/.cargo/bin/cargo test --test lib --no-fail-fast
      
workflows:
  version: 2.1

  build_and_test:
    jobs:
      - lint
      - clippy
      - build_and_test:
          matrix:
            parameters:
              toolchain: ["stable"]
