version: 2.1

jobs:
  lint:
    docker:
      - image: rust
    steps:
      - checkout
      - run:
          name: Install cargo fmt
          command: rustup component add rustfmt
      - run:
          name: Run lint
          command: cargo fmt -- --check

  clippy:
    docker:
      - image: rust
    steps:
      - checkout
      - run:
          name: Install cargo clippy
          command: rustup component add clippy
      - run:
          name: Run Clippy
          command: cargo clippy -- -W clippy::pedantic
  build_and_test:
    parameters:
      toolchain:
        description: rust toolchain
        type: string

    docker:
      - image: buildpack-deps:trusty

    steps:
      - checkout
      - run:
          name: update pyenv
          command: |
            # Install pyenv-update to allow addition of python 3.7.0
            git clone git://github.com/pyenv/pyenv-update.git $(pyenv root)/plugins/pyenv-update
            pyenv update
            pyenv install 3.7.0
      - run: |
          pyenv global 3.7.0
          sudo python -m pip install --upgrade pip setuptools wheel
          sudo python -m pip install pipenv
      - run: pip install localstack
      - run: localstack start
      - run: >
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | 
          sh -s -- -v -y --profile minimal --default-toolchain <<parameters.toolchain>>
      - run: $HOME/.cargo/bin/cargo build
      - run: $HOME/.cargo/bin/cargo test --locked  --no-fail-fast --lib
      - run: $HOME/.cargo/bin/cargo test --test lib --no-fail-fast
      
workflows:
  version: 2.1

  build_and_test:
    jobs:
      - lint
      - clippy
      - build_and_test:
          matrix:
            parameters:
              toolchain: ["stable"]
